config/routes.rb
Blog::Application.routes.draw do
 
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  mount RedactorRails::Engine => '/redactor_rails'

  devise_for :users

  match '/relation' ,:to => 'person#newrelation', :via => 'post'
  match '/relation' ,:to => 'person#killrelation', :via => 'delete'  

  match '/intro' , :to => 'home#intro'
  match '/blog/(:userid)/addpost' ,:to => 'person#newpost' 

  match '/profile/(:userid)', :to => 'person#profile'
  namespace :blog do
    match '/(:userid)' , :to => 'person#show'
  end

  resources :images 
  
  match 'post/(:userid)' ,:to => 'post#post' ,:via => 'post' ,:defaults => {:format => 'json'}
  match '/comment/(:postid)' => 'comment#post' , :via => 'post' , :defaults => {:format => 'json'}
  root :to => "home#index" 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper
  layout "application"
  def index
    @mostRecentUsers = mostRecentUser(3)
    @mostRecentPosts = mostRecentPost(3)
    @mostRecentImages = mostRecentImage(3)
  end
  def intro

  end
end

app/views/home/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p>George First Try on ROR </p>
    <p>Welcome to put your comment</p>
    <ul class="footer-links">
      <li><a>test</a></li>

    </ul>

  </div>
</footer>

app/views/home/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><a href="/">Home</a></li>
          <li><a href="/intro">Intro</a></li>
        </ul>
      </div>
      <div class="nav-collapse collapse rightright">
        <ul class="nav">
          <%if user_signed_in?%>
          <li><a href="/blog/<%=current_user.id%>">My Blog</a></li>
          <li><a href="/profile/<%=current_user.id%>">Profile</a></li>

          <li><%=link_to('Logout',destroy_user_session_path,:method => :delete)%></li>
          <%else%>
           <li><a href="#login" role="button" data-toggle="modal">Log In</a></li>
           <%end%>


        </ul>  
      </div>
    </div>
  </div>
</div>
<div id="login" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
    <h3 id="myModalLabel">Login</h3>
  </div>
  <div class="modal-body">
    <%= form_for("user", :url => user_session_path) do |f|%>
      <%= f.text_field :email%><br>
      <%= f.password_field :password%><br>
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
      <%= f.submit 'Sign In'%><br>
      <%= link_to "Forget your password?" ,new_password_path('user') %>
    <%end%>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/home/index.html.erb
<div class="hero-unit">
  <% @mostRecentUsers.each do |user|%>
  <a href="/blog/<%=user.id%>">
    <img src="<%=user.images[0].image.url(:thumb)%>">
  </a>
  <p></p>
  <%end%>

</div>
<% @mostRecentImages.each do |image|%>
    <img src="<%=image.image.url(:thumb)%>">
  <p></p>
  <%end%>